### ISSUE TITLE
clean_data function on train.py should be improved

### ISSUE THREAD

**Issue by murilommen** [udacity/nd00333_AZMLND_Optimizing_a_Pipeline_in_Azure-Starter_Files#1]
**Problem #1:** The function clean_data on train.py doesn't return x and y by default. 
**Problem #2:** The function is defined after it is called on the script

**How I'd solve:** 

*Problem #1*

``` 
    def clean_data(data):
    
     ...

       return x_df, y_df
``` 

*Problem #2*

```

if __name__ == '__main__':
   

    ds = ### YOUR CODE HERE###

    x, y = clean_data(ds)

    ### TRAIN TEST SPLIT HERE ###

    run = Run.get_context()
    
    main()

```

**Comment by scign** [comment]
I have submitted these corrections as a PR ([link](https://github.com/udacity/nd00333_AZMLND_Optimizing_a_Pipeline_in_Azure-Starter_Files/pull/2))

**Comment by abhiojha8** [comment]
Thanks! Merged the PR.
